jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: CROSS-LAPTOP\SQLEXPRESS
      port: 1433
      schema: dbo
      database: jaffle_shop
      trusted_connection: True

      